/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_APP_PB_H_INCLUDED
#define PB_APP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _VersionMsg {
    pb_callback_t version;
    pb_callback_t fileName;
    pb_callback_t minVersion;
} VersionMsg;

typedef struct _AppMsg {
    pb_callback_t name;
    pb_callback_t developer;
    pb_callback_t bundleid;
    pb_callback_t description;
    pb_callback_t versions;
    pb_callback_t iconurl;
    pb_callback_t fallback_iconurl;
} AppMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define VersionMsg_init_default                  {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define AppMsg_init_default                      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define VersionMsg_init_zero                     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define AppMsg_init_zero                         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define VersionMsg_version_tag                   1
#define VersionMsg_fileName_tag                  2
#define VersionMsg_minVersion_tag                3
#define AppMsg_name_tag                          1
#define AppMsg_developer_tag                     2
#define AppMsg_bundleid_tag                      3
#define AppMsg_description_tag                   4
#define AppMsg_versions_tag                      5
#define AppMsg_iconurl_tag                       6
#define AppMsg_fallback_iconurl_tag              7

/* Struct field encoding specification for nanopb */
#define VersionMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   version,           1) \
X(a, CALLBACK, REQUIRED, STRING,   fileName,          2) \
X(a, CALLBACK, REQUIRED, STRING,   minVersion,        3)
#define VersionMsg_CALLBACK pb_default_field_callback
#define VersionMsg_DEFAULT NULL

#define AppMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, CALLBACK, REQUIRED, STRING,   developer,         2) \
X(a, CALLBACK, REQUIRED, STRING,   bundleid,          3) \
X(a, CALLBACK, REQUIRED, STRING,   description,       4) \
X(a, CALLBACK, REPEATED, MESSAGE,  versions,          5) \
X(a, CALLBACK, REQUIRED, STRING,   iconurl,           6) \
X(a, CALLBACK, OPTIONAL, STRING,   fallback_iconurl,  7)
#define AppMsg_CALLBACK pb_default_field_callback
#define AppMsg_DEFAULT NULL
#define AppMsg_versions_MSGTYPE VersionMsg

extern const pb_msgdesc_t VersionMsg_msg;
extern const pb_msgdesc_t AppMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define VersionMsg_fields &VersionMsg_msg
#define AppMsg_fields &AppMsg_msg

/* Maximum encoded size of messages (where known) */
/* VersionMsg_size depends on runtime parameters */
/* AppMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
