/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_CATEGORIES_PB_H_INCLUDED
#define PB_CATEGORIES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CategoryMsg {
    pb_callback_t id;
    pb_callback_t name;
} CategoryMsg;

typedef struct _CategoriesMsg {
    pb_callback_t categories;
} CategoriesMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CategoryMsg_init_default                 {{{NULL}, NULL}, {{NULL}, NULL}}
#define CategoriesMsg_init_default               {{{NULL}, NULL}}
#define CategoryMsg_init_zero                    {{{NULL}, NULL}, {{NULL}, NULL}}
#define CategoriesMsg_init_zero                  {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define CategoryMsg_id_tag                       1
#define CategoryMsg_name_tag                     2
#define CategoriesMsg_categories_tag             1

/* Struct field encoding specification for nanopb */
#define CategoryMsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2)
#define CategoryMsg_CALLBACK pb_default_field_callback
#define CategoryMsg_DEFAULT NULL

#define CategoriesMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  categories,        1)
#define CategoriesMsg_CALLBACK pb_default_field_callback
#define CategoriesMsg_DEFAULT NULL
#define CategoriesMsg_categories_MSGTYPE CategoryMsg

extern const pb_msgdesc_t CategoryMsg_msg;
extern const pb_msgdesc_t CategoriesMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CategoryMsg_fields &CategoryMsg_msg
#define CategoriesMsg_fields &CategoriesMsg_msg

/* Maximum encoded size of messages (where known) */
/* CategoryMsg_size depends on runtime parameters */
/* CategoriesMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
