/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_CRASHREQ_PB_H_INCLUDED
#define PB_CRASHREQ_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CrashReportEntry {
    pb_callback_t data;
} CrashReportEntry;

typedef struct _CrashReportMsg {
    pb_callback_t entries;
} CrashReportMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CrashReportEntry_init_default            {{{NULL}, NULL}}
#define CrashReportMsg_init_default              {{{NULL}, NULL}}
#define CrashReportEntry_init_zero               {{{NULL}, NULL}}
#define CrashReportMsg_init_zero                 {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define CrashReportEntry_data_tag                1
#define CrashReportMsg_entries_tag               1

/* Struct field encoding specification for nanopb */
#define CrashReportEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1)
#define CrashReportEntry_CALLBACK pb_default_field_callback
#define CrashReportEntry_DEFAULT NULL

#define CrashReportMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           1)
#define CrashReportMsg_CALLBACK pb_default_field_callback
#define CrashReportMsg_DEFAULT NULL
#define CrashReportMsg_entries_MSGTYPE CrashReportEntry

extern const pb_msgdesc_t CrashReportEntry_msg;
extern const pb_msgdesc_t CrashReportMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CrashReportEntry_fields &CrashReportEntry_msg
#define CrashReportMsg_fields &CrashReportMsg_msg

/* Maximum encoded size of messages (where known) */
/* CrashReportEntry_size depends on runtime parameters */
/* CrashReportMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
