/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_NEWS_PB_H_INCLUDED
#define PB_NEWS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _NewsEntry {
    pb_callback_t author;
    pb_callback_t title;
    pb_callback_t body;
    pb_callback_t date;
    pb_callback_t link;
} NewsEntry;

typedef struct _NewsMsg {
    pb_callback_t news;
} NewsMsg;

typedef struct _Changelog {
    pb_callback_t version;
    pb_callback_t body;
} Changelog;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define NewsEntry_init_default                   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define NewsMsg_init_default                     {{{NULL}, NULL}}
#define Changelog_init_default                   {{{NULL}, NULL}, {{NULL}, NULL}}
#define NewsEntry_init_zero                      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define NewsMsg_init_zero                        {{{NULL}, NULL}}
#define Changelog_init_zero                      {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define NewsEntry_author_tag                     1
#define NewsEntry_title_tag                      2
#define NewsEntry_body_tag                       3
#define NewsEntry_date_tag                       4
#define NewsEntry_link_tag                       5
#define NewsMsg_news_tag                         1
#define Changelog_version_tag                    1
#define Changelog_body_tag                       2

/* Struct field encoding specification for nanopb */
#define NewsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   author,            1) \
X(a, CALLBACK, SINGULAR, STRING,   title,             2) \
X(a, CALLBACK, SINGULAR, STRING,   body,              3) \
X(a, CALLBACK, SINGULAR, STRING,   date,              4) \
X(a, CALLBACK, SINGULAR, STRING,   link,              5)
#define NewsEntry_CALLBACK pb_default_field_callback
#define NewsEntry_DEFAULT NULL

#define NewsMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  news,              1)
#define NewsMsg_CALLBACK pb_default_field_callback
#define NewsMsg_DEFAULT NULL
#define NewsMsg_news_MSGTYPE NewsEntry

#define Changelog_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   version,           1) \
X(a, CALLBACK, SINGULAR, STRING,   body,              2)
#define Changelog_CALLBACK pb_default_field_callback
#define Changelog_DEFAULT NULL

extern const pb_msgdesc_t NewsEntry_msg;
extern const pb_msgdesc_t NewsMsg_msg;
extern const pb_msgdesc_t Changelog_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define NewsEntry_fields &NewsEntry_msg
#define NewsMsg_fields &NewsMsg_msg
#define Changelog_fields &Changelog_msg

/* Maximum encoded size of messages (where known) */
/* NewsEntry_size depends on runtime parameters */
/* NewsMsg_size depends on runtime parameters */
/* Changelog_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
