/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SUGGESTIONS_PB_H_INCLUDED
#define PB_SUGGESTIONS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SuggestionMsg {
    pb_callback_t name;
    pb_callback_t bundleid;
} SuggestionMsg;

typedef struct _SuggestionsMsg {
    pb_callback_t suggestions;
} SuggestionsMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SuggestionMsg_init_default               {{{NULL}, NULL}, {{NULL}, NULL}}
#define SuggestionsMsg_init_default              {{{NULL}, NULL}}
#define SuggestionMsg_init_zero                  {{{NULL}, NULL}, {{NULL}, NULL}}
#define SuggestionsMsg_init_zero                 {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SuggestionMsg_name_tag                   1
#define SuggestionMsg_bundleid_tag               2
#define SuggestionsMsg_suggestions_tag           1

/* Struct field encoding specification for nanopb */
#define SuggestionMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, CALLBACK, REQUIRED, STRING,   bundleid,          2)
#define SuggestionMsg_CALLBACK pb_default_field_callback
#define SuggestionMsg_DEFAULT NULL

#define SuggestionsMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  suggestions,       1)
#define SuggestionsMsg_CALLBACK pb_default_field_callback
#define SuggestionsMsg_DEFAULT NULL
#define SuggestionsMsg_suggestions_MSGTYPE SuggestionMsg

extern const pb_msgdesc_t SuggestionMsg_msg;
extern const pb_msgdesc_t SuggestionsMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SuggestionMsg_fields &SuggestionMsg_msg
#define SuggestionsMsg_fields &SuggestionsMsg_msg

/* Maximum encoded size of messages (where known) */
/* SuggestionMsg_size depends on runtime parameters */
/* SuggestionsMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
