/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UPDATE_PB_H_INCLUDED
#define PB_UPDATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _UpdateMsg {
    pb_callback_t version;
    bool force;
    pb_callback_t changelog;
} UpdateMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define UpdateMsg_init_default                   {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define UpdateMsg_init_zero                      {{{NULL}, NULL}, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define UpdateMsg_version_tag                    1
#define UpdateMsg_force_tag                      2
#define UpdateMsg_changelog_tag                  3

/* Struct field encoding specification for nanopb */
#define UpdateMsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   version,           1) \
X(a, STATIC,   SINGULAR, BOOL,     force,             2) \
X(a, CALLBACK, SINGULAR, STRING,   changelog,         3)
#define UpdateMsg_CALLBACK pb_default_field_callback
#define UpdateMsg_DEFAULT NULL

extern const pb_msgdesc_t UpdateMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UpdateMsg_fields &UpdateMsg_msg

/* Maximum encoded size of messages (where known) */
/* UpdateMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
