/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_VTABLERESPONSE_PB_H_INCLUDED
#define PB_VTABLERESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _VTableEntryMsg {
    pb_callback_t name;
    pb_callback_t bundleid;
    pb_callback_t developer;
    pb_callback_t iconurl;
    pb_callback_t version;
    pb_callback_t fallback_iconurl;
} VTableEntryMsg;

typedef struct _VTableResponseMsg {
    pb_callback_t entries;
} VTableResponseMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define VTableEntryMsg_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define VTableResponseMsg_init_default           {{{NULL}, NULL}}
#define VTableEntryMsg_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define VTableResponseMsg_init_zero              {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define VTableEntryMsg_name_tag                  1
#define VTableEntryMsg_bundleid_tag              2
#define VTableEntryMsg_developer_tag             3
#define VTableEntryMsg_iconurl_tag               4
#define VTableEntryMsg_version_tag               5
#define VTableEntryMsg_fallback_iconurl_tag      6
#define VTableResponseMsg_entries_tag            1

/* Struct field encoding specification for nanopb */
#define VTableEntryMsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   bundleid,          2) \
X(a, CALLBACK, SINGULAR, STRING,   developer,         3) \
X(a, CALLBACK, SINGULAR, STRING,   iconurl,           4) \
X(a, CALLBACK, SINGULAR, STRING,   version,           5) \
X(a, CALLBACK, SINGULAR, STRING,   fallback_iconurl,  6)
#define VTableEntryMsg_CALLBACK pb_default_field_callback
#define VTableEntryMsg_DEFAULT NULL

#define VTableResponseMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           1)
#define VTableResponseMsg_CALLBACK pb_default_field_callback
#define VTableResponseMsg_DEFAULT NULL
#define VTableResponseMsg_entries_MSGTYPE VTableEntryMsg

extern const pb_msgdesc_t VTableEntryMsg_msg;
extern const pb_msgdesc_t VTableResponseMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define VTableEntryMsg_fields &VTableEntryMsg_msg
#define VTableResponseMsg_fields &VTableResponseMsg_msg

/* Maximum encoded size of messages (where known) */
/* VTableEntryMsg_size depends on runtime parameters */
/* VTableResponseMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
