import glob
import os
from SCons.Script import Dir, Environment

env = Environment()

Import("env")
env = env.Clone()

srcs = (
    glob.glob("./**/**.m", recursive=True)
    + glob.glob("./**/**.mm", recursive=True)
    + glob.glob("./**/**.c", recursive=True)
    + glob.glob("./**/**.cpp", recursive=True)
)
srcs = [s for s in srcs if not s.startswith("./deps/mbedtls/")]

project_dir = Dir("#").abspath
mbedtls_dir = os.path.join(project_dir, "deps", "mbedtls")
mbedtls_srcs = sorted(glob.glob(os.path.join(mbedtls_dir, "library", "*.c")))
mbedtls_env = env.Clone()
mbedtls_env["CFLAGS"] = [flag for flag in env["CFLAGS"] if flag not in ("-fobjc-arc", "-Werror")]
mbedtls_env["CPPFLAGS"] = [flag for flag in env["CPPFLAGS"] if flag != "-Werror"]
mbedtls_env.Append(
    CFLAGS=[
        "-I" + os.path.join(mbedtls_dir, "include"),
        "-DMBEDTLS_CONFIG_FILE='<mbedtls/config.h>'",
        "-Wno-unused-function",
        "-Wno-unused-variable",
    ],
    CPPFLAGS=[
        "-I" + os.path.join(mbedtls_dir, "include"),
        "-DMBEDTLS_CONFIG_FILE='<mbedtls/config.h>'",
    ],
)
mbedtls_lib = mbedtls_env.StaticLibrary("#xcbuild/libveteris_mbedtls", mbedtls_srcs)

srcs_to_remove_idx = []
for i in srcs:
    if "libobjcipc" in i or (
        ("YZLog" in i or "DebugTextView" in i) and env.get("debug", 0) == 0
    ):
        srcs_to_remove_idx.append(srcs.index(i))
srcs = [srcs[i] for i in range(len(srcs)) if i not in srcs_to_remove_idx]

static_libs = [
    "libs/libssl.a",
    "libs/libcurl.a",
    "libs/libcrypto.a",
]
if os.path.isfile("libs/libz.a"):
    static_libs.insert(0, "libs/libz.a")
else:
    static_libs.append("-lz")

env.Append(
    CFLAGS=[
        "-include", "Veteris/Veteris-Prefix.pch",
        "-I./Veteris/md5",
        "-I./Veteris",
        "-I./Veteris/ActionSheetPicker",
        "-I./Veteris/InAppSettingsKit/Models",
        "-I./Veteris/InAppSettingsKit/Controllers",
        "-I./Veteris/InAppSettingsKit/Views",
        "-I./Veteris/Classes",
        "-I./Veteris/Classes/Convenience",
        "-I./Veteris/Classes/../Clutch",
        "-I./Veteris/Classes/../Clutch/minizip",
        "-I./Veteris/Classes/AppInfo",
        "-I./Veteris/Classes/AppsTableViewController",
        "-I./Veteris/Classes/CategoriesTableViewController",
        "-I./Veteris/Classes/CategorySelectedViewController",
        "-I./Veteris/Classes/CrackTableViewCell",
        "-I./Veteris/Classes/CrackTableViewController",
        "-I./Veteris/Classes/CrackViewController",
        "-I./Veteris/Classes/FeaturedTableViewController",
        "-I./Veteris/Classes/SearchTableViewController",
        "-I./Veteris/Classes/SettingsTableViewController",
        "-I./Veteris/SVProgressHUD",
        "-I./KSCrash/Source/KSCrash/Reporting/Filters",
        "-I./KSCrash/Source/KSCrash/Reporting/Tools",
        "-I./KSCrash/Source/KSCrash/Recording",
        "-I./KSCrash/Source/KSCrash/Recording/Tools",
        "-I./KSCrash/Source/KSCrash/Recording/Filters/Tools",
        "-I./KSCrash/Source/KSCrash/Reporting/Filters/Tools",
        "-I./KSCrash/Source/KSCrash/Reporting/Sinks",
        "-I./KSCrash/Source/KSCrash/Recording/Sentry",
        "-I./KSCrash/Source/KSCrash/Installations",
        "-I.",
        "-I./Veteris/BBHTTP",
        "-I./Veteris/BBHTTP/Handlers",
        "-I./Veteris/BBHTTP/Internal",
        "-I./Veteris/Classes/HomeTableViewCell",
        "-I./SdkAdditions",
        "-I./SdkAdditions/MobileCoreServices",
        "-I./libobjcipc",
        "-I./deps/mbedtls/include",
        "-DHAVE_CERT",
        "-DVAPI",
    ],
    LINKFLAGS=[
        "-framework", "AppSupport",
        "-framework", "QuartzCore",
        "-framework", "CoreImage",
        "-framework", "Security",
        "-framework", "Foundation",
        "-framework", "UIKit",
        "-framework", "MobileInstallation",
        "-framework", "CoreGraphics",
        "-framework", "MobileCoreServices",
        "-framework", "MessageUI",
        "-framework", "SystemConfiguration",
    ] + static_libs + [
        "-Wl,-U,_MobileInstallationLookup",
        "-Wl,-U,_MobileInstallationInstall",
    ],
)
env.Prepend(LIBS=[mbedtls_lib])

veteris_prog = env.Program("#xcbuild/Veteris", srcs)
Return("veteris_prog")
